baseURL = "https://shouye0927.github.io/"
title = "壽也的部落"
theme = "PaperMod"
[languages.zh-tw]
languageName = "繁體中文"
weight = 1

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[params.assets]
  disableFingerprinting = true
  disableHLJS = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  noClasses = false  # 必須為 false，因為你產生的 CSS 檔是基於類別選擇器 (Class selectors)
  # style = '...'    # 可以留空或註解掉，因為你已經有了自訂的 CSS 檔案